# This workflow will install Python dependencies, run tests and lint/formatting - possibly with a variety of Python versions - bump version, re-commit  publish to PYPI
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Publish Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  package:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9"]
    permissions:
      id-token: write
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - uses: pdm-project/setup-pdm@v3
      with:
        version: 'head' 
        
    - name: Install dependencies
      run: |
        rm pdm.lock
        pdm install -G dev
        
    - name: Dryrun
      run: |
        pdm dryrun
        
    - name: Update version file with new version
      run: |
        pdm bump
        
    - name: Tag commit
      run: |
        pdm tag
        
    - name: Commit and Push version bump
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "Bump [skip actions]"
        
    - name: Publish
      run: |
        pdm pub


